
version: '3.8'

services:
  web:
    build: .
    container_name: hallazgos_web
    ports:
      - "8085:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    container_name: hallazgos_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hallazgos
      MYSQL_USER: usuario
      MYSQL_PASSWORD: secreto
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data: